vcom ../vhdl/basys3_util_pkg.vhd
vcom ../vhdl/counter_util_pkg.vhd
vcom ../vhdl/counter_comp_pkg.vhd
vcom ../vhdl/io_ctrl_.vhd
vcom ../vhdl/io_ctrl_rtl.vhd
vcom ../vhdl/counter_.vhd
vcom ../vhdl/counter_rtl.vhd
vcom ../vhdl/top_.vhd
vcom ../vhdl/top_struc.vhd
vcom ../tb/tb_top_sim.vhd