# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/work/design/VHDL_Kurs/counter/impl/counter.cache/wt [current_project]
set_property parent.project_path D:/work/design/VHDL_Kurs/counter/impl/counter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  D:/work/design/VHDL_Kurs/counter/vhdl/counter_util_pkg.vhd
  D:/work/design/VHDL_Kurs/counter/vhdl/counter_.vhd
  D:/work/design/VHDL_Kurs/counter/vhdl/basys3_util_pkg.vhd
  D:/work/design/VHDL_Kurs/counter/vhdl/counter_comp_pkg.vhd
  D:/work/design/VHDL_Kurs/counter/vhdl/top_.vhd
  D:/work/design/VHDL_Kurs/counter/vhdl/counter_rtl.vhd
  D:/work/design/VHDL_Kurs/counter/vhdl/top_struc.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/work/design/VHDL_Kurs/counter/impl/counter.srcs/constrs_1/new/counter_constr.xdc
set_property used_in_implementation false [get_files D:/work/design/VHDL_Kurs/counter/impl/counter.srcs/constrs_1/new/counter_constr.xdc]


synth_design -top top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
